# Generated by Django 4.2.2 on 2023-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("input_text", models.CharField(max_length=2500)),
                ("text_length", models.CharField(max_length=20)),
                ("is_genuine", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "news",
            },
        ),
    ]
