# Generated by Django 4.2.2 on 2023-06-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
