# Generated by Django 4.2.2 on 2023-06-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0003_alter_news_created_at_alter_news_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="is_genuine",
            new_name="genuine",
        ),
    ]
